import { StyleSheet } from '@react-pdf/renderer';

export const pdfStyles = StyleSheet.create({
  page: {
    paddingTop: 48,
    paddingBottom: 56,
    paddingHorizontal: 48,
    fontSize: 10,
    color: '#1f2937',
    fontFamily: 'Helvetica',
  },
  letterhead: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    borderBottomWidth: 1,
    borderBottomColor: '#cbd5e1',
    paddingBottom: 10,
    marginBottom: 18,
  },
  companyName: { fontSize: 14, fontFamily: 'Helvetica-Bold' },
  companyMeta: { fontSize: 9, color: '#475569', marginTop: 2 },
  documentTitle: {
    fontSize: 16,
    fontFamily: 'Helvetica-Bold',
    textAlign: 'center',
    marginBottom: 4,
  },
  documentSubtitle: {
    fontSize: 10,
    textAlign: 'center',
    color: '#475569',
    marginBottom: 18,
  },
  sectionTitle: {
    fontSize: 11,
    fontFamily: 'Helvetica-Bold',
    marginTop: 12,
    marginBottom: 6,
    textTransform: 'uppercase',
    letterSpacing: 0.5,
    color: '#0f172a',
  },
  paragraph: { fontSize: 10, lineHeight: 1.4, marginBottom: 6 },
  twoCol: { flexDirection: 'row', gap: 16 },
  twoColItem: { flex: 1 },
  fieldLabel: { fontSize: 8, color: '#64748b', textTransform: 'uppercase', letterSpacing: 0.4 },
  fieldValue: { fontSize: 10, marginTop: 1, marginBottom: 6 },
  table: { borderWidth: 1, borderColor: '#cbd5e1', borderRadius: 2 },
  tableRow: { flexDirection: 'row' },
  tableRowAlt: { backgroundColor: '#f8fafc' },
  tableCellLabel: {
    flex: 1,
    paddingVertical: 5,
    paddingHorizontal: 8,
    borderRightWidth: 1,
    borderRightColor: '#cbd5e1',
    fontFamily: 'Helvetica-Bold',
    color: '#0f172a',
  },
  tableCellValue: { flex: 2, paddingVertical: 5, paddingHorizontal: 8 },
  signatureBlock: { marginTop: 30, flexDirection: 'row', gap: 32 },
  signaturePane: { flex: 1 },
  signatureLine: {
    borderTopWidth: 1,
    borderTopColor: '#0f172a',
    marginTop: 36,
    marginBottom: 4,
  },
  signatureLabel: { fontSize: 9, color: '#475569' },
  footer: {
    position: 'absolute',
    bottom: 24,
    left: 48,
    right: 48,
    fontSize: 8,
    color: '#94a3b8',
    textAlign: 'center',
    borderTopWidth: 1,
    borderTopColor: '#e2e8f0',
    paddingTop: 6,
  },
});
